package com.example.telegrambot.model;

public enum AllMalfunction {

    LIQUID_LEAKING_FROM_UNDER_BOTTOM_CAR,

    UNKNOWN_RUDIMENTS_UNDER_BOTTOM_CAR,

    THE_NAVIGATION_DOOR_IS_NOT_CLOSED,

    DRIVERS_DOOR_IS_NOT_CLOSED,

    LEFT_REAR_DOOR_NOT_CLOSED,

    RIGHT_REAR_DOOR_NOT_CLOSED,

    LEFT_REAR_LIGHTING_FIXTURES_MALFUNCTION,

    RIGHT_REAR_LIGHT_INSTRUMENTS ,

    LEFT_FRONT_LIGHTING_FIXTURES ,

    RIGHT_FRONT_LIGHTING_FIXTURES_MALFUNCTION,

    LOWER_LEFT_FRONT_WHEEL,

    LOWER_RIGHT_FRONT_WHEEL,

    LOWER_LEFT_REAR_WHEEL,

    LOWER_RIGHT_REAR_WHEEL
}
